[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tagcn-bind"
version = "0.1.0"
description = "TAGCN binding affinity tools"
authors = [
    { name = "Will", email = "william.ogilvie2@outlook.com" }
]

dependencies = [
    "pandas"    
]

[tool.setuptools.packages.find]
where = ["src"]
