datasets:
  - name: "OOD_Test_test"
    data_csv_path: "data/OOD_Test_processed_test.csv"
    output_dir: "data/graphs/ODD_Test_test"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"
  - name: "OOD_Test_train"
    data_csv_path: "data/OOD_Test_processed_train.csv"
    output_dir: "data/graphs/OOD_Test_train"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"
  - name: "OOD_Test_val"
    data_csv_path: "data/OOD_Test_processed_val.csv"
    output_dir: "data/graphs/OOD_Test_val"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"

  - name: "OOD_Test_test_legacy"
    data_csv_path: "data/OOD_Test_processed_test.csv"
    output_dir: "data/graphs/OOD_Test_legacy_test"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_legacy_config.yml"
  - name: "OOD_Test_train_legacy"
    data_csv_path: "data/OOD_Test_processed_train.csv"
    output_dir: "data/graphs/OOD_Test_legacy_train"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_legacy_config.yml"
  - name: "OOD_Test_val_legacy"
    data_csv_path: "data/OOD_Test_processed_val.csv"
    output_dir: "data/graphs/OOD_Test_legacy_val"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_legacy_config.yml"
