datasets:
  - name: "CASF-2016"
    data_csv_path: "data/CASF_2016_processed.csv"
    output_dir: "data/graphs/CASF-2016"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"
  - name: "PDBbind_train"
    data_csv_path: "data/PDBbind_processed_train.csv"
    output_dir: "data/graphs/PDBbind_train"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"
  - name: "PDBbind_val"
    data_csv_path: "data/PDBbind_processed_val.csv"
    output_dir: "data/graphs/PDBbind_val"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"