datasets:
  - name: "Zero_Ligand_Bias_test"
    data_csv_path: "data/Zero_Ligand_Bias_processed_test.csv"
    output_dir: "data/graphs/Zero_Ligand_Bias_test"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"
  - name: "Zero_Ligand_Bias_train"
    data_csv_path: "data/Zero_Ligand_Bias_processed_train.csv"
    output_dir: "data/graphs/Zero_Ligand_Bias_train"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"
  - name: "Zero_Ligand_Bias_val"
    data_csv_path: "data/Zero_Ligand_Bias_processed_val.csv"
    output_dir: "data/graphs/Zero_Ligand_Bias_val"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_config.yml"

  - name: "Zero_Ligand_Bias_test_legacy"
    data_csv_path: "data/Zero_Ligand_Bias_processed_test.csv"
    output_dir: "data/graphs/Zero_Ligand_Bias_legacy_test"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_legacy_config.yml"
  - name: "Zero_Ligand_Bias_train_legacy"
    data_csv_path: "data/Zero_Ligand_Bias_processed_train.csv"
    output_dir: "data/graphs/Zero_Ligand_Bias_legacy_train"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_legacy_config.yml"
  - name: "Zero_Ligand_Bias_val_legacy"
    data_csv_path: "data/Zero_Ligand_Bias_processed_val.csv"
    output_dir: "data/graphs/Zero_Ligand_Bias_legacy_val"
    atom_keys_path: "config/PDB_Atom_Keys.csv"
    graph_gen_config_path: "config/graph_gen_legacy_config.yml"