output_dir: output/summary_plots
stats_dir: output/training_stats
predictions_dir: output/predictions
file_name_tag: 'grid_search_fewer_layers'
plots:
  bubble: true
  metrics_over_epochs: true
  true_vs_predicted: true
experiments:
- name: TAGCN-K-1-L-2-Dim-256-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-256-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-256-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-256-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-256-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-256-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-256-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-256-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-256-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-256-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-256-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-256-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-256-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-256-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-256-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-256-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-512-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-512-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-512-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-512-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-512-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-512-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-512-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-512-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-512-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-512-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-512-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-512-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-512-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-512-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-512-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-512-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-768-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-768-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-768-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-768-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-768-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-768-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-768-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-768-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-768-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-768-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-768-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-768-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-768-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-768-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-768-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-768-WD-0-30-1-Inter-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-256-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-256-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-256-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-256-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-256-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-256-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-256-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-256-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-256-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-256-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-256-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-256-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-256-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-256-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-256-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-256-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-512-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-512-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-512-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-512-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-512-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-512-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-512-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-512-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-768-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-768-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-768-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-768-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-1-L-2-Dim-768-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-L-2-Dim-768-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-3-L-2-Dim-768-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-K-2-1-L-2-Dim-768-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-768-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-768-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-768-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-768-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-768-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-768-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-3-L-2-Dim-768-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
- name: TAGCN-Drop-0-2-K-2-1-L-2-Dim-768-WD-0-30-1-Intra-OOD-Test
  time_stamp: '20260317_182500'
