output_dir: output/summary_plots
stats_dir: output/training_stats
predictions_dir: output/predictions
file_name_tag: 'fewer_layers_casf'
plots:
  bubble: true
  metrics_over_epochs: false
  true_vs_predicted: false
experiments: []
