output_dir: output/summary_plots
stats_dir: output/training_stats
predictions_dir: output/predictions
file_name_tag: 'hidden_dim_casf'
plots:
  bubble: true
  metrics_over_epochs: false
  true_vs_predicted: true
  bubble_labels: true
  alternate_labels: true
  bootstrap_bars: false
  title: "CASF-2016" 
experiments:
- name: TAGCN-Drop-0-2-K-3-L-5-Dim-768-Intra-CASF-2016
  alternate_label: "TAGCN (K=3 768 Dim)"
  time_stamp: '20260406_163300'
- name: TAGCN-Drop-0-2-K-3-L-5-Dim-256-Intra-CASF-2016
  alternate_label: "TAGCN (K=3 256 Dim)"
  time_stamp: '20260324_092900'
- name: TAGCN-Drop-0-2-K-2-L-5-Dim-256-Intra-CASF-2016
  alternate_label: "TAGCN (K=2 256 Dim)" 
  time_stamp: '20260406_163300'
- name: TAGCN-Drop-0-2-K-2-L-5-Dim-768-Intra-CASF-2016
  alternate_label: "TAGCN (K=2 768 Dim)" 
  time_stamp: '20260406_163300'
- name: TAGCN-Drop-0-2-K-3-L-5-Dim-512-Intra-CASF-2016
  alternate_label: "TAGCN (K=3 512 Dim)" 
  time_stamp: '20260409_163400'
- name: TAGCN-Drop-0-2-K-2-L-5-Dim-512-Intra-CASF-2016
  alternate_label: "TAGCN (K=2 512 Dim)" 
  time_stamp: '20260409_163400'