output_dir: output/summary_plots
stats_dir: output/training_stats
predictions_dir: output/predictions
file_name_tag: 'GATv2_Reg_Zero'
plots:
  bubble: true
  metrics_over_epochs: false
  true_vs_predicted: true
  bubble_labels: true
  alternate_labels: true
  bootstrap_bars: false
  title: "0 Ligand Bias"
experiments:
- name: GATv2-H-3-L-5-Dim-256-Inter-Zero-Ligand-Bias
  alternate_label: GATv2 (Base)
  time_stamp: '20260324_092900'
- name: GATv2-H-3-L-5-Dim-256-WD-0-30-1-Inter-Zero-Ligand-Bias
  alternate_label: GATv2 (Weight Decay)
  time_stamp: '20260324_092900'
- name: GATv2-Drop-0-2-H-3-L-5-Dim-256-Inter-Zero-Ligand-Bias
  alternate_label: GATv2 (Dropout)
  time_stamp: '20260324_092900'
- name: GATv2-Drop-0-2-H-3-L-5-Dim-256-WD-0-30-1-Inter-Zero-Ligand-Bias
  alternate_label: GATv2 (Dropout + Weight Decay)
  time_stamp: '20260324_092900'

