output_dir: output/summary_plots
stats_dir: output/training_stats
predictions_dir: output/predictions
file_name_tag: '20260308_083000'
plots:
  bubble: true
  metrics_over_epochs: true
  true_vs_predicted: true
experiments:
- name: TAGCN-K-1-L-5-Dim-768-Intra-OOD-Test
  time_stamp: '20260308_082900'
- name: TAGCN-K-1-L-5-Dim-768-Inter-OOD-Test
  time_stamp: '20260308_082900'
- name: GATv2-H-3-L-5-Dim-768-Intra-OOD-Test
  time_stamp: '20260308_082900'
- name: GATv2-H-3-L-5-Dim-768-Inter-OOD-Test
  time_stamp: '20260308_082900'
