experiments:
- name: TAGCN-K-1-L-2-Dim-512-Intra-OOD-Test
  run_id: '20260310_200900'
  args:
    model: TAGCN
    epochs: 300
    batch_size: 128
    lr: 0.001
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 512
    head: 1
    K: 1
    dropout_rate: 0.0
    num_GNN_layers: 2
    activation_function: leaky_relu
    weight_decay: 0.0
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/OOD_Test_scaling.pt
    train_data_csv: data/OOD_Test_processed_train.csv
    val_data_csv: data/OOD_Test_processed_val.csv
    test_data_csv: data/OOD_Test_processed_test.csv
    train_graphs_dir: data/graphs/OOD_Test_train
    val_graphs_dir: data/graphs/OOD_Test_val
    test_graphs_dir: data/graphs/OOD_Test_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
- name: TAGCN-K-2-L-2-Dim-512-Intra-OOD-Test
  run_id: '20260310_200900'
  args:
    model: TAGCN
    epochs: 300
    batch_size: 128
    lr: 0.001
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 512
    head: 1
    K: 2
    dropout_rate: 0.0
    num_GNN_layers: 2
    activation_function: leaky_relu
    weight_decay: 0.0
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/OOD_Test_scaling.pt
    train_data_csv: data/OOD_Test_processed_train.csv
    val_data_csv: data/OOD_Test_processed_val.csv
    test_data_csv: data/OOD_Test_processed_test.csv
    train_graphs_dir: data/graphs/OOD_Test_train
    val_graphs_dir: data/graphs/OOD_Test_val
    test_graphs_dir: data/graphs/OOD_Test_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
- name: TAGCN-K-1-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  run_id: '20260310_200900'
  args:
    model: TAGCN
    epochs: 300
    batch_size: 128
    lr: 0.001
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 512
    head: 1
    K: 1
    dropout_rate: 0.0
    num_GNN_layers: 2
    activation_function: leaky_relu
    weight_decay: 0.0001
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/OOD_Test_scaling.pt
    train_data_csv: data/OOD_Test_processed_train.csv
    val_data_csv: data/OOD_Test_processed_val.csv
    test_data_csv: data/OOD_Test_processed_test.csv
    train_graphs_dir: data/graphs/OOD_Test_train
    val_graphs_dir: data/graphs/OOD_Test_val
    test_graphs_dir: data/graphs/OOD_Test_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
- name: TAGCN-K-2-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  run_id: '20260310_200900'
  args:
    model: TAGCN
    epochs: 300
    batch_size: 128
    lr: 0.001
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 512
    head: 1
    K: 2
    dropout_rate: 0.0
    num_GNN_layers: 2
    activation_function: leaky_relu
    weight_decay: 0.0001
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/OOD_Test_scaling.pt
    train_data_csv: data/OOD_Test_processed_train.csv
    val_data_csv: data/OOD_Test_processed_val.csv
    test_data_csv: data/OOD_Test_processed_test.csv
    train_graphs_dir: data/graphs/OOD_Test_train
    val_graphs_dir: data/graphs/OOD_Test_val
    test_graphs_dir: data/graphs/OOD_Test_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-512-Intra-OOD-Test
  run_id: '20260310_200900'
  args:
    model: TAGCN_v2
    epochs: 300
    batch_size: 128
    lr: 0.001
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 512
    head: 1
    K: 1
    dropout_rate: 0.2
    num_GNN_layers: 2
    activation_function: leaky_relu
    weight_decay: 0.0
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/OOD_Test_scaling.pt
    train_data_csv: data/OOD_Test_processed_train.csv
    val_data_csv: data/OOD_Test_processed_val.csv
    test_data_csv: data/OOD_Test_processed_test.csv
    train_graphs_dir: data/graphs/OOD_Test_train
    val_graphs_dir: data/graphs/OOD_Test_val
    test_graphs_dir: data/graphs/OOD_Test_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-512-Intra-OOD-Test
  run_id: '20260310_200900'
  args:
    model: TAGCN_v2
    epochs: 300
    batch_size: 128
    lr: 0.001
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 512
    head: 1
    K: 2
    dropout_rate: 0.2
    num_GNN_layers: 2
    activation_function: leaky_relu
    weight_decay: 0.0
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/OOD_Test_scaling.pt
    train_data_csv: data/OOD_Test_processed_train.csv
    val_data_csv: data/OOD_Test_processed_val.csv
    test_data_csv: data/OOD_Test_processed_test.csv
    train_graphs_dir: data/graphs/OOD_Test_train
    val_graphs_dir: data/graphs/OOD_Test_val
    test_graphs_dir: data/graphs/OOD_Test_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
- name: TAGCN-Drop-0-2-K-1-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  run_id: '20260310_200900'
  args:
    model: TAGCN_v2
    epochs: 300
    batch_size: 128
    lr: 0.001
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 512
    head: 1
    K: 1
    dropout_rate: 0.2
    num_GNN_layers: 2
    activation_function: leaky_relu
    weight_decay: 0.0001
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/OOD_Test_scaling.pt
    train_data_csv: data/OOD_Test_processed_train.csv
    val_data_csv: data/OOD_Test_processed_val.csv
    test_data_csv: data/OOD_Test_processed_test.csv
    train_graphs_dir: data/graphs/OOD_Test_train
    val_graphs_dir: data/graphs/OOD_Test_val
    test_graphs_dir: data/graphs/OOD_Test_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
- name: TAGCN-Drop-0-2-K-2-L-2-Dim-512-WD-0-30-1-Intra-OOD-Test
  run_id: '20260310_200900'
  args:
    model: TAGCN_v2
    epochs: 300
    batch_size: 128
    lr: 0.001
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 512
    head: 1
    K: 2
    dropout_rate: 0.2
    num_GNN_layers: 2
    activation_function: leaky_relu
    weight_decay: 0.0001
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/OOD_Test_scaling.pt
    train_data_csv: data/OOD_Test_processed_train.csv
    val_data_csv: data/OOD_Test_processed_val.csv
    test_data_csv: data/OOD_Test_processed_test.csv
    train_graphs_dir: data/graphs/OOD_Test_train
    val_graphs_dir: data/graphs/OOD_Test_val
    test_graphs_dir: data/graphs/OOD_Test_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
