experiments:
- name: GATv2-H-3-L-5-Dim-256-Inter-Zero-Ligand-Bias
  run_id: '20260321_161700'
  args:
    model: GATv2
    epochs: 300
    batch_size: 32
    lr: 0.000103
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 256
    head: 3
    K: 3
    dropout_rate: 0.0
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/Zero_Ligand_Bias_legacy_scaling.pt
    train_data_csv: data/Zero_Ligand_Bias_processed_train.csv
    val_data_csv: data/Zero_Ligand_Bias_processed_val.csv
    test_data_csv: data/Zero_Ligand_Bias_processed_test.csv
    train_graphs_dir: data/graphs/Zero_Ligand_Bias_legacy_train
    val_graphs_dir: data/graphs/Zero_Ligand_Bias_legacy_val
    test_graphs_dir: data/graphs/Zero_Ligand_Bias_legacy_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
- name: GATv2-H-3-L-5-Dim-256-Intra-Zero-Ligand-Bias
  run_id: '20260321_161700'
  args:
    model: GATv2
    epochs: 300
    batch_size: 32
    lr: 0.000103
    early_stopping: 100
    early_stopping_metric: pearson_rolling
    hidden_dim: 256
    head: 3
    K: 3
    dropout_rate: 0.0
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0
    seeds:
    - 100
    - 123
    - 15
    - 257
    - 2
    - 2012
    - 3752
    - 350
    - 843
    - 621
    standardise_aevs: false
    standardise_targets: true
    scaling_stats_pt: data/scaling/Zero_Ligand_Bias_scaling.pt
    train_data_csv: data/Zero_Ligand_Bias_processed_train.csv
    val_data_csv: data/Zero_Ligand_Bias_processed_val.csv
    test_data_csv: data/Zero_Ligand_Bias_processed_test.csv
    train_graphs_dir: data/graphs/Zero_Ligand_Bias_train
    val_graphs_dir: data/graphs/Zero_Ligand_Bias_val
    test_graphs_dir: data/graphs/Zero_Ligand_Bias_test
    model_save_dir: output/models
    predictions_save_dir: output/predictions
    save_training_stats_dir: output/training_stats
    plots_dir: output/plots_dir
