experiments:
- name: AEV-PLIG-OOD-Test-New-Graphs-128-Batch
  run_id: "20260225_160107" 
  args:
    model: GATv2 
    epochs: 1000 # high epochs for early stopping
    batch_size: 128
    lr: 0.001
    early_stopping: 50
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 256
    head: 3
    K: 3 # Not relavant to GATv2
    dropout_rate: 0.0 # Not relavant to GATv2
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621]  
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

- name: AEV-PLIG-OOD-Test-New-Graphs-Pearson-128-Batch
  run_id: "20260225_160107"
  args:
    model: GATv2 
    epochs: 1000 # high epochs for early stopping
    batch_size: 128
    lr: 0.001
    early_stopping: 50
    early_stopping_metric: "pearson" # choose mse, kendall, or pearson
    hidden_dim: 256
    head: 3
    K: 3 # Not relavant to GATv2
    dropout_rate: 0.0 # Not relavant to GATv2
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621]  
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

   

- name: AEV-PLIG-OOD-Test-New-Graphs-MSE-128-Batch
  run_id: "20260225_160107"
  args:
    model: GATv2 
    epochs: 1000 # high epochs for early stopping
    batch_size: 128
    lr: 0.001
    early_stopping: 50
    early_stopping_metric: "mse" # choose mse, kendall, or pearson
    hidden_dim: 256
    head: 3
    K: 3 # Not relavant to GATv2
    dropout_rate: 0.0 # Not relavant to GATv2
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621]  
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

- name: AEV-PLIG-OOD-Test-New-Graphs-64-Batch
  run_id: "20260225_160107"
  args:
    model: GATv2 
    epochs: 1000 # high epochs for early stopping
    batch_size: 64
    lr: 0.0005 # halved learning rate as halved batch size
    early_stopping: 80 # increased early stopping patience as dropped batch size (plots show makes kendall more noisy)
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 256
    head: 3
    K: 3 # Not relavant to GATv2
    dropout_rate: 0.0 # Not relavant to GATv2
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621]  
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

- name: AEV-PLIG-OOD-Test-New-Graphs-32-Batch
  run_id: "20260225_160107"
  args:
    model: GATv2 
    epochs: 1000 # high epochs for early stopping
    batch_size: 32
    lr: 0.00025 # halved learning rate as halved batch size
    early_stopping: 100 # increased early stopping patience as dropped batch size (plots show makes kendall more noisy)
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 256
    head: 3
    K: 3 # Not relavant to GATv2
    dropout_rate: 0.0 # Not relavant to GATv2
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621]  
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

  
- name: TAGCN-K-1-L-5-OOD-Test-New-Graphs-Scaled-Hidden-Dim-128-Batch
  run_id: "20260225_160107"
  args:
    model: TAGCN 
    epochs: 1000 # high epochs for early stopping
    batch_size: 128
    lr: 0.001
    early_stopping: 50
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 768 # this is scaled to match AEV-PLIG 
    head: 3 # Not relevant to TAGCN
    K: 1 
    dropout_rate: 0.0 # Not relevant to OG TAGCN
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621] 
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

   
- name: TAGCN-K-1-L-5-OOD-Test-New-Graphs-Pearson-Scaled-Hidden-Dim-128-Batch
  run_id: "20260225_160107"
  args:
    model: TAGCN 
    epochs: 1000 # high epochs for early stopping
    batch_size: 128
    lr: 0.001
    early_stopping: 50
    early_stopping_metric: "pearson" # choose mse, kendall, or pearson
    hidden_dim: 768 # this is scaled to match AEV-PLIG 
    head: 3 # Not relevant to TAGCN
    K: 1 
    dropout_rate: 0.0 # Not relevant to OG TAGCN
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621] 
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

   
- name: TAGCN-K-1-L-5-OOD-Test-New-Graphs-MSE-Scaled-Hidden-Dim-128-Batch
  run_id: "20260225_160107"
  args:
    model: TAGCN 
    epochs: 1000 # high epochs for early stopping
    batch_size: 128
    lr: 0.001
    early_stopping: 50
    early_stopping_metric: "mse" # choose mse, kendall, or pearson
    hidden_dim: 768 # this is scaled to match AEV-PLIG 
    head: 3 # Not relevant to TAGCN
    K: 1 
    dropout_rate: 0.0 # Not relevant to OG TAGCN
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621] 
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

- name: TAGCN-K-1-L-5-OOD-Test-New-Graphs-Scaled-Hidden-Dim-64-Batch
  run_id: "20260225_160107"
  args:
    model: TAGCN 
    epochs: 1000 # high epochs for early stopping
    batch_size: 64
    lr: 0.0005
    early_stopping: 80
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 768 # this is scaled to match AEV-PLIG 
    head: 3 # Not relevant to TAGCN
    K: 1 
    dropout_rate: 0.0 # Not relevant to OG TAGCN
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621] 
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

   
- name: TAGCN-K-1-L-5-OOD-Test-New-Graphs-Scaled-Hidden-Dim-32-Batch
  run_id: "20260225_160107"
  args:
    model: TAGCN 
    epochs: 1000 # high epochs for early stopping
    batch_size: 32
    lr: 0.00025
    early_stopping: 100
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 768 # this is scaled to match AEV-PLIG 
    head: 3 # Not relevant to TAGCN
    K: 1 
    dropout_rate: 0.0 # Not relevant to OG TAGCN
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621] 
    scaling_stats_pt: "data/scaling/OOD_Test_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_train" 
    val_graphs_dir: "data/graphs/OOD_Test_val"
    test_graphs_dir: "data/graphs/OOD_Test_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

   
- name: AEV-PLIG-OOD-Test-Legacy-Graphs-128-Batch
  run_id: "20260225_160107"
  args:
    model: GATv2 
    epochs: 1000 # high epochs for early stopping
    batch_size: 128
    lr: 0.001
    early_stopping: 50
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 256
    head: 3
    K: 3 # Not relavant to GATv2
    dropout_rate: 0.0 # Not relavant to GATv2
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621]  
    scaling_stats_pt: "data/scaling/OOD_Test_legacy_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_legacy_train" 
    val_graphs_dir: "data/graphs/OOD_Test_legacy_val"
    test_graphs_dir: "data/graphs/OOD_Test_legacy_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

- name: AEV-PLIG-OOD-Test-Legacy-Graphs-64-Batch
  run_id: "20260225_160107"
  args:
    model: GATv2 
    epochs: 1000 # high epochs for early stopping
    batch_size: 64
    lr: 0.0005 # halved learning rate as halved batch size
    early_stopping: 80 # increased early stopping patience as dropped batch size (plots show makes kendall more noisy)
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 256
    head: 3
    K: 3 # Not relavant to GATv2
    dropout_rate: 0.0 # Not relavant to GATv2
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621]  
    scaling_stats_pt: "data/scaling/OOD_Test_legacy_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_legacy_train" 
    val_graphs_dir: "data/graphs/OOD_Test_legacy_val"
    test_graphs_dir: "data/graphs/OOD_Test_legacy_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

   

- name: AEV-PLIG-OOD-Test-Legacy-Graphs-32-Batch
  run_id: "20260225_160107"
  args:
    model: GATv2 
    epochs: 1000 # high epochs for early stopping
    batch_size: 32
    lr: 0.00025 # halved learning rate as halved batch size
    early_stopping: 100 # increased early stopping patience as dropped batch size (plots show makes kendall more noisy)
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 256
    head: 3
    K: 3 # Not relavant to GATv2
    dropout_rate: 0.0 # Not relavant to GATv2
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621]  
    scaling_stats_pt: "data/scaling/OOD_Test_legacy_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_legacy_train" 
    val_graphs_dir: "data/graphs/OOD_Test_legacy_val"
    test_graphs_dir: "data/graphs/OOD_Test_legacy_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

   
- name: TAGCN-K-1-L-5-OOD-Test-Legacy-Graphs-Scaled-Hidden-Dim-128-Batch
  run_id: "20260225_160107"
  args:
    model: TAGCN 
    epochs: 1000 # high epochs for early stopping
    batch_size: 128
    lr: 0.001
    early_stopping: 50
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 768 # this is scaled to match AEV-PLIG 
    head: 3 # Not relevant to TAGCN
    K: 1 
    dropout_rate: 0.0 # Not relevant to OG TAGCN
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621] 
    scaling_stats_pt: "data/scaling/OOD_Test_legacy_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_legacy_train" 
    val_graphs_dir: "data/graphs/OOD_Test_legacy_val"
    test_graphs_dir: "data/graphs/OOD_Test_legacy_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

   

- name: TAGCN-K-1-L-5-OOD-Test-Legacy-Graphs-Scaled-Hidden-Dim-64-Batch
  run_id: "20260225_160107"
  args:
    model: TAGCN 
    epochs: 1000 # high epochs for early stopping
    batch_size: 64
    lr: 0.0005
    early_stopping: 80
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 768 # this is scaled to match AEV-PLIG 
    head: 3 # Not relevant to TAGCN
    K: 1 
    dropout_rate: 0.0 # Not relevant to OG TAGCN
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621] 
    scaling_stats_pt: "data/scaling/OOD_Test_legacy_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_legacy_train" 
    val_graphs_dir: "data/graphs/OOD_Test_legacy_val"
    test_graphs_dir: "data/graphs/OOD_Test_legacy_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

- name: TAGCN-K-1-L-5-OOD-Test-Legacy-Graphs-Scaled-Hidden-Dim-32-Batch
  run_id: "20260225_160107"
  args:
    model: TAGCN 
    epochs: 1000 # high epochs for early stopping
    batch_size: 32
    lr: 0.00025
    early_stopping: 100
    early_stopping_metric: "kendall" # choose mse, kendall, or pearson
    hidden_dim: 768 # this is scaled to match AEV-PLIG 
    head: 3 # Not relevant to TAGCN
    K: 1 
    dropout_rate: 0.0 # Not relevant to OG TAGCN
    num_GNN_layers: 5
    activation_function: leaky_relu
    weight_decay: 0.0001 # Explore this
    seeds: [100, 123, 15, 257, 2, 2012, 3752, 350, 843, 621] 
    scaling_stats_pt: "data/scaling/OOD_Test_legacy_scaling.pt" 
    train_data_csv: "data/OOD_Test_processed_train.csv"
    val_data_csv: "data/OOD_Test_processed_val.csv"
    test_data_csv: "data/OOD_Test_processed_test.csv"    
    train_graphs_dir: "data/graphs/OOD_Test_legacy_train" 
    val_graphs_dir: "data/graphs/OOD_Test_legacy_val"
    test_graphs_dir: "data/graphs/OOD_Test_legacy_test"
    model_save_dir: "output/models"
    predictions_save_dir: "output/predictions"
    save_training_stats_dir: "output/training_stats"
    plots_dir: "output/plots_dir"   

